## Potential bugs in backpropagation
```sh
/mnt/hdd4T/www_home/miniconda3/envs/c3dgs/bin/python /mnt/hdd4T/www_home/project/learn/gaussian-splatting/merge_test.py -s dataset/tandt/train -m output/merge_debug/train/merge_debug_train_view_dependent --eval --start_checkpoint output/view_dependent/chkpnt30000.pth --iterations 3000 --merge_interval 100 --merge_points_num 50000 
[500, 1000, 1500, 2000, 2500, 3000]
Checkpoint will be saved in the following iterations: [3000]
Optimizing output/merge_debug/train/merge_debug_train_view_dependent_ITER_3000_MI_100_MPN_50000
ITER = Iterations
MI = Merge Interval
MPN = Merge Points Number
Namespace(checkpoint_iterations=[3000], compute_cov3D_python=False, convert_SHs_python=False, data_device='cuda', debug=False, debug_from=-1, densification_interval=100, densify_from_iter=500, densify_grad_threshold=0.0002, densify_until_iter=15000, detect_anomaly=False, eval=True, feature_lr=0.0025, images='images', ip='127.0.0.1', iterations=3000, lambda_dssim=0.2, max_hashmap=19, merge_interval=100, merge_points_num=50000, model_path='output/merge_debug/train/merge_debug_train_view_dependent_ITER_3000_MI_100_MPN_50000', net_lr=0.01, net_lr_step=[5000, 15000, 25000], opacity_lr=0.05, opacity_reset_interval=3000, percent_dense=0.01, port=6009, position_lr_delay_mult=0.01, position_lr_final=1.6e-06, position_lr_init=0.00016, position_lr_max_steps=30000, quiet=False, random_background=False, resolution=-1, rotation_lr=0.001, save_iterations=[3000], scaling_lr=0.005, sh_degree=3, source_path='dataset/tandt/train', start_checkpoint='output/view_dependent/chkpnt30000.pth', test_iterations=[500, 1000, 1500, 2000, 2500, 3000], white_background=False) [15/09 00:14:24]
Output folder: output/merge_debug/train/merge_debug_train_view_dependent_ITER_3000_MI_100_MPN_50000 [15/09 00:14:24]
Reading camera 301/301 [15/09 00:14:26]
Loading Training Cameras [15/09 00:14:26]
Loading Test Cameras [15/09 00:14:30]
Number of points at initialisation :  182686 [15/09 00:14:31]
Start merging... [15/09 00:14:31]
Number of Gaussians before merging: 986409 [15/09 00:14:31]
Training progress:   0%|          | 0/2999 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/mnt/hdd4T/www_home/project/learn/gaussian-splatting/merge_test.py", line 312, in <module>
    args.merge_points_num)
  File "/mnt/hdd4T/www_home/project/learn/gaussian-splatting/merge_test.py", line 136, in training
    loss.backward()
  File "/mnt/hdd4T/www_home/miniconda3/envs/c3dgs/lib/python3.7/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/mnt/hdd4T/www_home/miniconda3/envs/c3dgs/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: Function _RasterizeGaussiansBackward returned an invalid gradient at index 1 - got [1061432, 3] but expected shape compatible with [939791, 3]
Training progress:   0%|          | 0/2999 [00:01<?, ?it/s]
```
## bugs in points number resolved
- real points number after merge: 964814

## Backpropagation of selection mask
